services:

  nifi:
    ports:
      - "8443:8443"
      - "8081:8081"
    image: apache/nifi:latest
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: nifinifinifi
      NIFI_JVM_HEAP_MAX: 2g
    links:
      - mongodb

  mongodb:
    ports:
      - "27017:27017"
    image: mongo:latest
