services:
  nifi:
    ports:
      - "8443:8443"
    image: apache/nifi:latest
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: nifinifinifi
      NIFI_JVM_HEAP_MAX: 2g
    links:
      - elasticsearch
      - mongodb
      - mysql
  mysql:
    image: mysql:latest
    container_name: iabd-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD: iabd
      MYSQL_DATABASE: retail_db
      MYSQL_USER: iabd
      MYSQL_PASSWORD: iabd
  mongodb:
    ports:
      - "27017:27017"
    image: mongo:latest
